import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import localFont from 'next/font/local';
import Footer from '@/Components/Footer/Footer';
import Header from '@/Components/Header/Header';
import BootstrapClient from '@/Components/BootstrapClient/BootstrapClient';



// fonts
const corbert = localFont({
  src: "../../public/fonts/Corbert-Medium.woff2",
  variable: "--font-corbert", 
});

const roboto = localFont({
  src: "../../public/fonts/Roboto-Regular.woff2",
  variable: "--font-roboto", 
});



export const metadata = {
  title: "DN Designs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" className={`${corbert.variable} ${roboto.variable}`}>
      <body>
      <BootstrapClient/>
      <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
