import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Footer from '@/Components/Footer/Footer';
import Header from '@/Components/Header/Header';

export const metadata = {
  title: "DN Designs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
